runtime: python37

env_variables:
  DB_USER: anant
  DB_PASSWORD: tnana
  DB_HOST: 172.16.32.3
  DB_DATABASE: employee
  raise_on_warnings: True
  CORS_VAL: *

vpc_access_connector:
name: "projects/exemplary-sign-360717/locations/us-central1/connectors/sql-connector"